# Generated by Django 5.1.15 on 2026-08-19 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benchmarkevaluation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='researchsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='benchmarkevaluation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='benchmarkevaluation',
            index=models.Index(fields=['user', '-created_at'], name='api_benchma_user_id_28706e_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['user', '-created_at'], name='api_researc_user_id_6a48ee_idx'),
        ),
    ]
