# Generated by Django 6.1 on 2026-08-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_tags_chat_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
